/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const languages = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "hi", label: "Hindi", nativeLabel: "Hindi" },
  { code: "te", label: "Telugu", nativeLabel: "Telugu" },
];

const legacyLanguageMap = {
  English: "en",
  Hindi: "hi",
  Telugu: "te",
};

const translations = {
  en: {
    appName: "DigiNest",
    appSubtitle: "Citizen document vault",
    searchPlaceholder: "Search documents, family records, requests",
    notifications: "Notifications",
    openUserMenu: "Open account menu",
    logout: "Logout",
    loggedInAs: "Logged in as",
    accountSaved: "Account saved in MongoDB users collection",
    userId: "User ID",
    dashboard: "Dashboard",
    documents: "Documents",
    documentMindmap: "Document Mindmap",
    consent: "Consent",
    history: "History",
    lifeEvents: "Life Events",
    family: "Family",
    reminders: "Reminders",
    lifeGraph: "Life Graph",
    settings: "Settings",
    home: "Home",
    docs: "Docs",
    share: "Share",
    more: "More",
    privacyPulse: "Privacy pulse",
    privacyPulseText: "3 active shares. Every link auto-expires.",
    welcomeBack: "Welcome back, {name}!",
    recordsReady: "Your citizen records are organized, protected, and ready. 10 documents total.",
    reviewPending: "Review pending consent requests, renew important documents, and keep your family timeline up to date.",
    addDocument: "Add Document",
    shareDocument: "Share Document",
    viewMindmap: "View Mindmap",
    addFamilyMember: "Add Family Member",
    viewReminders: "View Reminders",
    documentHealthScore: "Document Health Score",
    identityProofs: "All identity proofs verified and current",
    verifiedDocuments: "Verified Documents",
    healthSafetyStatus: "Health & Safety Status",
    vaccinationRecords: "Vaccination records up to date",
    vaccinationActive: "Vaccination Record - Active",
    healthInsuranceActive: "Health Insurance - Active until 31 Mar 2026",
    actionItemsRenewals: "Action Items & Renewals",
    upcomingReminders: "{count} upcoming reminders",
    viewAll: "View all",
    familyRecords: "Family Records",
    familyMembers: "{count} family members",
    manageFamily: "Manage family",
    documentIntelligence: "Document Intelligence",
    exploreClusters: "Explore connected document clusters",
    mindmapDescription: "View how your documents relate to each other through an AI-powered mindmap.",
    exploreMindmap: "Explore Mindmap",
    urgentAttention: "Urgent Attention",
    documentsNeedAction: "{count} documents need action",
    recentDocuments: "Recent Documents",
    consentAccess: "Consent & Access",
    activeAccessRisk: "Active Access Risk",
    pendingRequests: "{count} pending request{plural}",
    allAccessReviewed: "All access reviewed",
    pendingConsents: "Pending Consents",
    noPendingRequests: "No pending requests",
    viewAllRequests: "View all {count} requests",
    upcomingRemindersTitle: "Upcoming Reminders",
    lifeTimeline: "Life Timeline",
    settingsTitle: "Settings & Preferences",
    settingsDescription: "Customize your DigiNest experience with appearance, language, and privacy controls.",
    appearanceTheme: "Appearance & Theme",
    language: "Language",
    languageDescription: "Choose your preferred language",
    themeMode: "Theme Mode",
    themeModeDescription: "Choose light, dark, or automatic based on system",
    light: "Light",
    dark: "Dark",
    auto: "Auto",
    emotional: "Emotional",
    colorPsychologyMode: "Color Psychology Mode",
    colorPsychologyDescription: "Enhanced emotion-based document identification system",
    enhancedRecommended: "Enhanced (Recommended)",
    enhancedDescription: "Full color psychology - each document type has its own emotion",
    standard: "Standard",
    standardDescription: "Classic blue & neutral color scheme",
    interfaceMode: "Interface Mode",
    interfaceModeDescription: "Choose your interaction style",
    manualMode: "Manual Mode",
    manualDescription: "Full control with detailed options and granular settings",
    voiceMode: "Voice-Assisted Mode",
    voiceDescription: "Voice commands and guided workflows (requires microphone)",
    elderMode: "Elder/Simple Mode",
    elderDescription: "Larger text, simplified actions, and reduced visual complexity",
    privacySecurity: "Privacy & Security",
    requireAiConsent: "Require consent before AI summaries",
    requireAiConsentDescription: "AI processing always requires your explicit approval",
    autoExpireLinks: "Auto-expire shared links",
    autoExpireLinksDescription: "All shared links automatically expire after set duration",
    showAccessAlerts: "Show access alerts",
    showAccessAlertsDescription: "Receive notifications when your data is accessed",
    sessionAccount: "Session & Account",
    databaseStatus: "Database status",
    databaseStatusDescription: "After registration, MongoDB creates the users collection and stores this account.",
    collection: "Collection",
    savedFields: "Saved fields",
    colorReference: "Color Psychology Reference",
    identity: "Identity",
    identityDesc: "Trust, strength",
    health: "Health",
    healthDesc: "Safety, wellness",
    remindersLegend: "Reminders",
    remindersDesc: "Attention, clarity",
    familyLegend: "Family",
    familyDesc: "Love, connection",
    intelligence: "Intelligence",
    intelligenceDesc: "Creativity, AI",
    risk: "Risk",
    riskDesc: "Urgency, action",
    needHelp: "Need Help?",
    helpDocs: "Check our documentation for detailed guides",
    helpSupport: "Contact support at support@diginest.io",
    helpCommunity: "Join our community forum for tips and tricks",
    selectLanguage: "Select language",
  },
  hi: {
    appName: "DigiNest",
    appSubtitle: "नागरिक दस्तावेज़ वॉल्ट",
    searchPlaceholder: "दस्तावेज़, परिवार रिकॉर्ड, अनुरोध खोजें",
    notifications: "सूचनाएं",
    openUserMenu: "खाता मेनू खोलें",
    logout: "लॉगआउट",
    loggedInAs: "लॉग इन उपयोगकर्ता",
    accountSaved: "खाता MongoDB users collection में सेव है",
    userId: "यूज़र ID",
    dashboard: "डैशबोर्ड",
    documents: "दस्तावेज़",
    documentMindmap: "दस्तावेज़ माइंडमैप",
    consent: "सहमति",
    history: "इतिहास",
    lifeEvents: "जीवन घटनाएं",
    family: "परिवार",
    reminders: "रिमाइंडर",
    lifeGraph: "जीवन ग्राफ",
    settings: "सेटिंग्स",
    home: "होम",
    docs: "डॉक्स",
    share: "शेयर",
    more: "और",
    privacyPulse: "प्राइवेसी पल्स",
    privacyPulseText: "3 सक्रिय शेयर. हर लिंक अपने आप समाप्त होता है.",
    welcomeBack: "वापसी पर स्वागत है, {name}!",
    recordsReady: "आपके नागरिक रिकॉर्ड व्यवस्थित, सुरक्षित और तैयार हैं. कुल 10 दस्तावेज़.",
    reviewPending: "लंबित सहमति अनुरोध देखें, जरूरी दस्तावेज़ नवीनीकृत करें, और परिवार टाइमलाइन अपडेट रखें.",
    addDocument: "दस्तावेज़ जोड़ें",
    shareDocument: "दस्तावेज़ शेयर करें",
    viewMindmap: "माइंडमैप देखें",
    addFamilyMember: "परिवार सदस्य जोड़ें",
    viewReminders: "रिमाइंडर देखें",
    documentHealthScore: "दस्तावेज़ हेल्थ स्कोर",
    identityProofs: "सभी पहचान प्रमाण सत्यापित और वर्तमान हैं",
    verifiedDocuments: "सत्यापित दस्तावेज़",
    healthSafetyStatus: "स्वास्थ्य और सुरक्षा स्थिति",
    vaccinationRecords: "टीकाकरण रिकॉर्ड अपडेट हैं",
    vaccinationActive: "टीकाकरण रिकॉर्ड - सक्रिय",
    healthInsuranceActive: "स्वास्थ्य बीमा - 31 मार्च 2026 तक सक्रिय",
    actionItemsRenewals: "कार्य और नवीनीकरण",
    upcomingReminders: "{count} आने वाले रिमाइंडर",
    viewAll: "सभी देखें",
    familyRecords: "परिवार रिकॉर्ड",
    familyMembers: "{count} परिवार सदस्य",
    manageFamily: "परिवार प्रबंधित करें",
    documentIntelligence: "दस्तावेज़ इंटेलिजेंस",
    exploreClusters: "जुड़े दस्तावेज़ समूह देखें",
    mindmapDescription: "AI माइंडमैप से देखें कि आपके दस्तावेज़ एक-दूसरे से कैसे जुड़े हैं.",
    exploreMindmap: "माइंडमैप खोलें",
    urgentAttention: "तुरंत ध्यान दें",
    documentsNeedAction: "{count} दस्तावेज़ों पर कार्रवाई चाहिए",
    recentDocuments: "हाल के दस्तावेज़",
    consentAccess: "सहमति और एक्सेस",
    activeAccessRisk: "सक्रिय एक्सेस जोखिम",
    pendingRequests: "{count} लंबित अनुरोध",
    allAccessReviewed: "सभी एक्सेस समीक्षा हो चुकी है",
    pendingConsents: "लंबित सहमतियां",
    noPendingRequests: "कोई लंबित अनुरोध नहीं",
    viewAllRequests: "सभी {count} अनुरोध देखें",
    upcomingRemindersTitle: "आने वाले रिमाइंडर",
    lifeTimeline: "जीवन टाइमलाइन",
    settingsTitle: "सेटिंग्स और पसंद",
    settingsDescription: "दिखावट, भाषा और प्राइवेसी नियंत्रणों से DigiNest अनुभव बदलें.",
    appearanceTheme: "दिखावट और थीम",
    language: "भाषा",
    languageDescription: "अपनी पसंदीदा भाषा चुनें",
    themeMode: "थीम मोड",
    themeModeDescription: "लाइट, डार्क या सिस्टम के अनुसार चुनें",
    light: "लाइट",
    dark: "डार्क",
    auto: "ऑटो",
    emotional: "इमोशनल",
    colorPsychologyMode: "कलर साइकोलॉजी मोड",
    colorPsychologyDescription: "भावना आधारित दस्तावेज़ पहचान प्रणाली",
    enhancedRecommended: "उन्नत (सुझावित)",
    enhancedDescription: "हर दस्तावेज़ प्रकार के लिए अलग भावना वाला पूरा कलर सिस्टम",
    standard: "स्टैंडर्ड",
    standardDescription: "क्लासिक नीला और न्यूट्रल रंग",
    interfaceMode: "इंटरफ़ेस मोड",
    interfaceModeDescription: "अपनी उपयोग शैली चुनें",
    manualMode: "मैनुअल मोड",
    manualDescription: "विस्तृत विकल्पों और सेटिंग्स के साथ पूरा नियंत्रण",
    voiceMode: "वॉइस-असिस्टेड मोड",
    voiceDescription: "वॉइस कमांड और गाइडेड वर्कफ़्लो (माइक्रोफ़ोन चाहिए)",
    elderMode: "एल्डर/सिंपल मोड",
    elderDescription: "बड़ा टेक्स्ट, सरल actions, और कम visual complexity",
    privacySecurity: "प्राइवेसी और सुरक्षा",
    requireAiConsent: "AI summaries से पहले सहमति लें",
    requireAiConsentDescription: "AI processing हमेशा आपकी स्पष्ट अनुमति से होगी",
    autoExpireLinks: "शेयर लिंक auto-expire करें",
    autoExpireLinksDescription: "सभी शेयर लिंक तय समय के बाद अपने आप समाप्त होंगे",
    showAccessAlerts: "एक्सेस alerts दिखाएं",
    showAccessAlertsDescription: "डेटा एक्सेस होने पर सूचना पाएं",
    sessionAccount: "सेशन और खाता",
    databaseStatus: "डेटाबेस स्थिति",
    databaseStatusDescription: "Registration के बाद MongoDB users collection बनाकर यह account सेव करता है.",
    collection: "Collection",
    savedFields: "सेव fields",
    colorReference: "कलर साइकोलॉजी संदर्भ",
    identity: "पहचान",
    identityDesc: "भरोसा, मजबूती",
    health: "स्वास्थ्य",
    healthDesc: "सुरक्षा, wellness",
    remindersLegend: "रिमाइंडर",
    remindersDesc: "ध्यान, स्पष्टता",
    familyLegend: "परिवार",
    familyDesc: "प्यार, जुड़ाव",
    intelligence: "इंटेलिजेंस",
    intelligenceDesc: "रचनात्मकता, AI",
    risk: "जोखिम",
    riskDesc: "तत्कालता, action",
    needHelp: "मदद चाहिए?",
    helpDocs: "विस्तृत guides के लिए documentation देखें",
    helpSupport: "support@diginest.io पर support से संपर्क करें",
    helpCommunity: "Tips और tricks के लिए community forum join करें",
    selectLanguage: "भाषा चुनें",
  },
  te: {
    appName: "DigiNest",
    appSubtitle: "పౌర పత్రాల వాల్ట్",
    searchPlaceholder: "పత్రాలు, కుటుంబ రికార్డులు, అభ్యర్థనలు వెతకండి",
    notifications: "నోటిఫికేషన్లు",
    openUserMenu: "ఖాతా మెనూ తెరవండి",
    logout: "లాగౌట్",
    loggedInAs: "లాగిన్ అయిన వ్యక్తి",
    accountSaved: "ఖాతా MongoDB users collection లో సేవ్ అయింది",
    userId: "యూజర్ ID",
    dashboard: "డాష్‌బోర్డ్",
    documents: "పత్రాలు",
    documentMindmap: "పత్రాల మైండ్‌మ్యాప్",
    consent: "సమ్మతి",
    history: "చరిత్ర",
    lifeEvents: "జీవిత సంఘటనలు",
    family: "కుటుంబం",
    reminders: "రిమైండర్లు",
    lifeGraph: "జీవిత గ్రాఫ్",
    settings: "సెట్టింగ్స్",
    home: "హోమ్",
    docs: "డాక్స్",
    share: "షేర్",
    more: "మరిన్ని",
    privacyPulse: "ప్రైవసీ పల్స్",
    privacyPulseText: "3 active shares. ప్రతి link auto-expire అవుతుంది.",
    welcomeBack: "తిరిగి స్వాగతం, {name}!",
    recordsReady: "మీ పౌర రికార్డులు క్రమబద్ధంగా, భద్రంగా, సిద్ధంగా ఉన్నాయి. మొత్తం 10 పత్రాలు.",
    reviewPending: "Pending consent requests చూడండి, ముఖ్యమైన పత్రాలు renew చేయండి, కుటుంబ timeline update గా ఉంచండి.",
    addDocument: "పత్రం జోడించండి",
    shareDocument: "పత్రం షేర్ చేయండి",
    viewMindmap: "మైండ్‌మ్యాప్ చూడండి",
    addFamilyMember: "కుటుంబ సభ్యుని జోడించండి",
    viewReminders: "రిమైండర్లు చూడండి",
    documentHealthScore: "పత్రాల హెల్త్ స్కోర్",
    identityProofs: "అన్ని identity proofs verified గా ఉన్నాయి",
    verifiedDocuments: "Verified Documents",
    healthSafetyStatus: "ఆరోగ్య & భద్రత స్థితి",
    vaccinationRecords: "Vaccination records up to date",
    vaccinationActive: "Vaccination Record - Active",
    healthInsuranceActive: "Health Insurance - 31 Mar 2026 వరకు Active",
    actionItemsRenewals: "Action Items & Renewals",
    upcomingReminders: "{count} upcoming reminders",
    viewAll: "అన్నీ చూడండి",
    familyRecords: "కుటుంబ రికార్డులు",
    familyMembers: "{count} కుటుంబ సభ్యులు",
    manageFamily: "కుటుంబం నిర్వహించండి",
    documentIntelligence: "పత్రాల ఇంటెలిజెన్స్",
    exploreClusters: "కనెక్ట్ అయిన document clusters చూడండి",
    mindmapDescription: "AI-powered mindmap ద్వారా మీ పత్రాలు ఎలా కలుస్తాయో చూడండి.",
    exploreMindmap: "మైండ్‌మ్యాప్ తెరవండి",
    urgentAttention: "తక్షణ శ్రద్ధ",
    documentsNeedAction: "{count} పత్రాలకు action అవసరం",
    recentDocuments: "ఇటీవలి పత్రాలు",
    consentAccess: "సమ్మతి & యాక్సెస్",
    activeAccessRisk: "Active Access Risk",
    pendingRequests: "{count} pending request{plural}",
    allAccessReviewed: "అన్ని access reviewed",
    pendingConsents: "Pending Consents",
    noPendingRequests: "Pending requests లేవు",
    viewAllRequests: "{count} requests అన్నీ చూడండి",
    upcomingRemindersTitle: "రాబోయే రిమైండర్లు",
    lifeTimeline: "జీవిత టైమ్‌లైన్",
    settingsTitle: "సెట్టింగ్స్ & ప్రాధాన్యతలు",
    settingsDescription: "Appearance, language, privacy controls తో DigiNest experience మార్చండి.",
    appearanceTheme: "Appearance & Theme",
    language: "భాష",
    languageDescription: "మీకు ఇష్టమైన భాష ఎంచుకోండి",
    themeMode: "Theme Mode",
    themeModeDescription: "Light, dark, లేదా system automatic ఎంచుకోండి",
    light: "Light",
    dark: "Dark",
    auto: "Auto",
    emotional: "Emotional",
    colorPsychologyMode: "Color Psychology Mode",
    colorPsychologyDescription: "Emotion-based document identification system",
    enhancedRecommended: "Enhanced (Recommended)",
    enhancedDescription: "ప్రతి document type కు తన emotion తో పూర్తి color psychology",
    standard: "Standard",
    standardDescription: "Classic blue & neutral color scheme",
    interfaceMode: "Interface Mode",
    interfaceModeDescription: "మీ interaction style ఎంచుకోండి",
    manualMode: "Manual Mode",
    manualDescription: "Detailed options మరియు granular settings తో పూర్తి control",
    voiceMode: "Voice-Assisted Mode",
    voiceDescription: "Voice commands మరియు guided workflows (microphone అవసరం)",
    elderMode: "Elder/Simple Mode",
    elderDescription: "పెద్ద text, simplified actions, reduced visual complexity",
    privacySecurity: "ప్రైవసీ & భద్రత",
    requireAiConsent: "AI summaries కు ముందు consent అవసరం",
    requireAiConsentDescription: "AI processing ఎప్పుడూ మీ explicit approval తోనే జరుగుతుంది",
    autoExpireLinks: "Shared links auto-expire చేయండి",
    autoExpireLinksDescription: "అన్ని shared links set duration తర్వాత auto-expire అవుతాయి",
    showAccessAlerts: "Access alerts చూపించండి",
    showAccessAlertsDescription: "మీ data access అయినప్పుడు notifications పొందండి",
    sessionAccount: "Session & Account",
    databaseStatus: "Database status",
    databaseStatusDescription: "Registration తర్వాత MongoDB users collection create చేసి ఈ account ని save చేస్తుంది.",
    collection: "Collection",
    savedFields: "Saved fields",
    colorReference: "Color Psychology Reference",
    identity: "Identity",
    identityDesc: "Trust, strength",
    health: "Health",
    healthDesc: "Safety, wellness",
    remindersLegend: "Reminders",
    remindersDesc: "Attention, clarity",
    familyLegend: "Family",
    familyDesc: "Love, connection",
    intelligence: "Intelligence",
    intelligenceDesc: "Creativity, AI",
    risk: "Risk",
    riskDesc: "Urgency, action",
    needHelp: "సహాయం కావాలా?",
    helpDocs: "Detailed guides కోసం documentation చూడండి",
    helpSupport: "support@diginest.io ను contact చేయండి",
    helpCommunity: "Tips and tricks కోసం community forum join చేయండి",
    selectLanguage: "భాష ఎంచుకోండి",
  },
};

const LanguageContext = createContext();

function normalizeLanguage(value) {
  if (!value) return "en";
  if (translations[value]) return value;
  return legacyLanguageMap[value] || "en";
}

function interpolate(template, values = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key) => values[key] ?? "");
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => normalizeLanguage(localStorage.getItem("language")));

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      languages,
      setLanguage: (nextLanguage) => setLanguageState(normalizeLanguage(nextLanguage)),
      t: (key, values) => interpolate(translations[language]?.[key] || translations.en[key] || key, values),
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
